# Generated by Django 4.1.3 on 2022-11-05 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goles',
            name='fecha_ref',
            field=models.DateField(default=1987, verbose_name='%Y-%m-%d'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='goles',
            name='fecha',
            field=models.DateField(verbose_name='%Y-%m-%d'),
        ),
    ]
